'use strict';
// Content comes from the supplied professional profile. No external services or trackers.
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svgPaths = {
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>', down:'<path d="M12 4v16m-6-6 6 6 6-6"/>', up:'<path d="M12 20V4m-6 6 6-6 6 6"/>', chevron:'<path d="m6 9 6 6 6-6"/>', close:'<path d="m6 6 12 12M18 6 6 18"/>',
 mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>', phone:'<path d="M6.5 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-2.5l-5-2-2 2a15.4 15.4 0 0 1-7.5-7.5l2-2z"/>', linkedin:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 10v7m4 0v-7m0 3a3 3 0 0 1 6 0v4"/><circle cx="7" cy="7" r=".7"/>', location:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>', copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H4v13h4"/>', external:'<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>',
 grc:'<path d="m12 3 8 3v6c0 4-4 7-8 9-4-2-8-5-8-9V6Z"/><path d="m8 12 3 3 5-6"/>', qual:'<path d="m12 3 3 2 4 1 1 4 1 3-3 3-1 4-5-1-5 1-1-4-3-3 1-3 1-4 4-1Z"/><path d="m8 12 3 3 5-6"/>', iso:'<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 8h8M8 12h5M8 16h7"/>', bpm:'<rect x="8" y="3" width="8" height="5" rx="1"/><rect x="2" y="16" width="7" height="5" rx="1"/><rect x="15" y="16" width="7" height="5" rx="1"/><path d="M12 8v4m-7 4v-4h14v4"/>', pm:'<rect x="3" y="6" width="18" height="15" rx="2"/><path d="M8 6V3h8v3M3 12h18m-11 0v3h4v-3"/>', aud:'<path d="M13 3H4v18h10m-6-14h4M8 11h2"/><circle cx="15.5" cy="13.5" r="4.5"/><path d="m19 17 3 4"/>', lead:'<circle cx="12" cy="7" r="3"/><path d="M6 21v-4a6 6 0 0 1 12 0v4M5 10a2 2 0 0 0-2 3v2m16-5a2 2 0 0 1 2 3v2"/>', cx:'<path d="M21 12a9 9 0 0 1-9 9H4l2-4a9 9 0 1 1 15-5Z"/><path d="M8 11h8m-6 4h4"/>', education:'<path d="m2 9 10-5 10 5-10 5Z"/><path d="M6 11v6q6 5 12 0v-6m4-2v8"/>', certificate:'<path d="M6 3h12v12H6Z"/><path d="M9 7h6M9 11h6m-6 4-1 6 4-2 4 2-1-6"/>', role:'<path d="M4 21V3h10v18M8 7h2M8 11h2M8 15h2m4-6h6v12H2m15-8h1m-1 4h1"/>', globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18m-9-9c-6 6-6 12 0 18 6-6 6-12 0-18"/>'
};
function icon(name, extra=''){return `<svg class="${extra}" viewBox="0 0 24 24" aria-hidden="true">${svgPaths[name]||svgPaths.grc}</svg>`;}
const UI = {
 ar:{profile:'الملف المهني التنفيذي',eyebrow:'الجودة · الحوكمة · التميّز',shortPosition:'قيادة الجودة والحوكمة والتميّز التشغيلي',projectCTA:'استكشف المشاريع',contact:'لنتواصل',download:'السيرة الذاتية',scroll:'اكتشف المسيرة',location:'الرياض، المملكة العربية السعودية',feature:'مشروع بارز',details:'استكشف المشروع',scope:'نطاق المشروع',role:'الدور في المشروع',modalContact:'تواصل مع أحمد',six:'مشاريع مختارة',all:'جميع المشاريع',policy:'السياسات',governance:'الحوكمة والالتزام',operations:'التحوّل المؤسسي',projectsTitle:'المشاريع <span class="first-word">أولًا</span><br>والتفاصيل تصنع الفرق.',projectsIntro:'من السياسات الوطنية إلى تطوير أنظمة المؤسسات. ستة مشاريع تعكس مجالات عمل أحمد في الجودة والحوكمة وإدارة المشاريع.',skillsTitle:'خبرة تتكامل.<br>ورؤية تجمع التفاصيل.',skillsIntro:'ستة مجالات تجمع بين هندسة الأنظمة، والحوكمة، وقيادة التنفيذ. افتح كل مجال لاستكشافه.',coreSkills:'مهارات تدعم التنفيذ',coreSkillsDesc:'من تحليل العمليات إلى إدارة التغيير وقيادة الفرق.',careerSince:'مسيرة بدأت بهندسة العمليات، ثم اتسعت إلى الجودة والاستشارات والقيادة.',certCount:'13 شهادة مهنية',certIntro:'الهندسة وإدارة الأعمال، مع شهادات مهنية في الحوكمة وإدارة المشاريع والجودة والتدقيق.',credentialsTitle:'أساس علمي.<br>ومعرفة تتجدّد.',credentialsLabel:'المؤهلات والشهادات',organizationsTitle:'خبرة عبر جهات متعددة',organizationsIntro:'جهات العمل والمهام الاستشارية والعمل الحر، مع توضيح طبيعة العلاقة بكل جهة.',deviceTitle:'ملف واحد.<br>على كل شاشة.',deviceIntro:'اطّلع على السيرة المهنية الكاملة بالعربية أو الإنجليزية.',cvArabic:'السيرة بالعربية',cvEnglish:'السيرة بالإنجليزية',deviceCaption:'الملف المهني الرقمي والسيرة الذاتية - متاحان بالعربية والإنجليزية',close:'إغلاق التفاصيل',openMenu:'فتح القائمة',closeMenu:'إغلاق القائمة',copyEmail:'نسخ البريد الإلكتروني',copyPhone:'نسخ رقم الهاتف',copyError:'تعذر النسخ تلقائيًا. يمكنك تحديد بيانات التواصل ونسخها.',footer:'© 2026 أحمد بخاري · الملف المهني التنفيذي',filterResult:n=>`${n} من 6 مشاريع`,certResult:n=>`${n} من 13 شهادة`,originalPortrait:'الصورة الشخصية لأحمد بخاري',languages:'العربية والإنجليزية',nav:{home:'الرئيسية',projects:'المشاريع',expertise:'الخبرات',experience:'المسيرة',credentials:'المؤهلات',contact:'التواصل'},scopeMODON:'أنظمة الإدارة ومجالات التطبيق',viewAll:'استعرض جميع المشاريع',contactTitle:'بداية الحوار.<br>خطوة نحو التعاون.'},
 en:{profile:'EXECUTIVE PROFILE',eyebrow:'QUALITY · GOVERNANCE · EXCELLENCE',shortPosition:'Quality, GRC & Operational Excellence',projectCTA:'Explore projects',contact:'Let’s connect',download:'Curriculum vitae',scroll:'Discover the journey',location:'Riyadh, Saudi Arabia',feature:'Featured engagement',details:'Explore project',scope:'Project scope',role:'Project role',modalContact:'Connect with Ahmed',six:'selected projects',all:'All projects',policy:'Policy',governance:'Governance & compliance',operations:'Enterprise transformation',projectsTitle:'Projects first.<br>Details that matter.',projectsIntro:'From national policy to enterprise management systems. Six projects reflecting Ahmed’s work in quality, governance and project management.',skillsTitle:'Connected expertise.<br>A complete perspective.',skillsIntro:'Six disciplines bringing systems thinking, governance and delivery together. Open an area to explore its focus.',coreSkills:'Capabilities behind the work',coreSkillsDesc:'From process analysis to change management and team leadership.',careerSince:'A career that began in process engineering and grew into quality, consulting and leadership.',certCount:'13 professional certifications',certIntro:'Engineering and business foundations, complemented by credentials in governance, project management, quality and auditing.',credentialsTitle:'Strong foundations.<br>Continuous development.',credentialsLabel:'Education & credentials',organizationsTitle:'Experience across organizations',organizationsIntro:'Employers, consulting assignments and freelance engagements, with each relationship clearly identified.',deviceTitle:'One profile.<br>Every perspective.',deviceIntro:'Explore the full professional CV in English or Arabic.',cvArabic:'Arabic CV',cvEnglish:'English CV',deviceCaption:'Digital professional profile and CV - available in Arabic and English',close:'Close project details',openMenu:'Open navigation',closeMenu:'Close navigation',copyEmail:'Copy email address',copyPhone:'Copy phone number',copyError:'Automatic copy failed. Select and copy the contact information instead.',footer:'© 2026 Ahmed Bukhari · Executive profile',filterResult:n=>`${n} of 6 projects`,certResult:n=>`${n} of 13 certifications`,originalPortrait:'Professional portrait of Ahmed Bukhari',languages:'Arabic & English',nav:{home:'Home',projects:'Projects',expertise:'Expertise',experience:'Experience',credentials:'Credentials',contact:'Contact'},scopeMODON:'Management systems & focus areas',viewAll:'View all projects',contactTitle:'A conversation.<br>A new possibility.'}
};
let language='en';
// Start each page load in English; Arabic remains available from the language switch.
let projectFilter='all', certificateFilter='all', activeSection='home', observer, revealObserver;
const projectCategories={modon:'operations',pj1:'policy',pj2:'governance',pj4:'operations',pj5:'governance',pj6:'operations'};
const projectOrder=['modon','pj1','pj2','pj4','pj5','pj6'];
function icon3d(name){return `<img class="icon-3d" src="${assetURL(`assets/icons/${name}-navy-teal.png`)}" width="256" height="256" alt="" loading="lazy" aria-hidden="true">`;}
function diagram(kind){const name=({law:'law',cms:'compliance',epm:'process',gov:'governance',rst:'restructure'})[kind]||'compliance';return localVisual('assets/projects/'+name+'-icon.png','','icon-3d project-topic-icon');}
function hub(){const ar=language==='ar';return `<div class="scope-panel"><span class="scope-heading">${ar?'نطاق مشروع مدن':'MODON project scope'}</span><div class="scope-locations"><div><strong>${ar?'١':'1'}</strong><span>${ar?'المقر الرئيسي':'Headquarters'}</span></div><span class="scope-plus" aria-hidden="true">+</span><div><strong>${ar?'٣٥':'35'}</strong><span>${ar?'مدينة صناعية':'Industrial cities'}</span></div></div><p class="scope-note">${ar?'شمل العمل المقر الرئيسي والمدن الصناعية ضمن نطاق المشروع.':'The project covered headquarters and industrial cities.'}</p><div class="scope-work"><div>${icon3d('bpm')}<span><strong>${ar?'٧ مشاريع':'7 projects'}</strong>${ar?'لأنظمة الإدارة':'for management systems'}</span></div><div>${icon3d('qual')}<span><strong>${ar?'مشروع واحد':'1 project'}</strong>${ar?'لثقافة الجودة':'for quality culture'}</span></div></div></div>`;}

function sectionHeader(number,label,title,description=''){return `<div class="section-header"><div><div class="section-number"><span>${number}</span><span>${esc(label)}</span></div><h2>${title}</h2></div>${description?`<p>${esc(description)}</p>`:''}</div>`;}
function pdfLink(lang,label,cls='secondary'){return `<a class="button ${cls}" href="${assetURL(`Ahmed_Bukhari_CV_Updated_${lang.toUpperCase()}.pdf`)}" download>${icon('download')}<span>${esc(label)}</span></a>`;}
function organizationLogo(key){const logos={"MHRSD": "assets/organizations/mhrsd-supplied.png", "SAC": "assets/organizations/sac-supplied.png", "SDC": "assets/organizations/sdc-supplied.png", "DVT": "assets/organizations/dvt-supplied.png", "MDN": "assets/organizations/mdn-supplied.png", "AFC": "assets/organizations/afc-supplied.png", "BTM": "assets/organizations/btm-supplied.png", "ATL": "assets/organizations/atl-supplied.png", "NTP": "assets/organizations/ntp-supplied.png"};return logos[key]?`<div class="organization-logo-panel">${localVisual(logos[key],key,"organization-logo")}</div>`:"";}
function projectOrganization(key){return organizationLogo(({modon:"MDN",pj1:"MHRSD",pj4:"SDC",pj5:"SDC",pj6:"ATL"})[key]);}
function projectCard(key){const p=D[language][key],u=UI[language];return `<article class="project-card" data-project-item="${key}" data-category="${projectCategories[key]}"><div class="project-illustration">${diagram(p.g)}</div><div class="project-card-body">${projectOrganization(key)}<span class="project-context">${esc(p.ctx)}</span><h3>${esc(p.t)}</h3><p>${esc(p.d)}</p><div class="project-card-footer"><span class="project-role">${icon('pm')}${esc(p.role||p.tags.join(' · '))}</span><button class="detail-link" data-open-project="${key}" aria-label="${esc(u.details+' - '+p.t)}">${esc(u.details)}${icon('arrow','direction-arrow')}</button></div></div></article>`;}
function render(){
 const d=D[language],u=UI[language],m=d.modon;
 document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';
 document.title=language==='ar'?'أحمد بخاري | الملف المهني التنفيذي':'Ahmed Bukhari | Executive Profile';
 $('meta[name="description"]').content=d.intro;
 $('#brandCaption').textContent=u.profile;$('#headerContact').innerHTML=esc(u.contact)+icon('arrow','direction-arrow');$('#footerCopy').textContent=u.footer;$('#backTop').innerHTML=esc(d.top)+icon('up');$('#backTop').ariaLabel=d.top;$('#closeDialog').ariaLabel=u.close;$('.skip').textContent=language==='ar'?'انتقل إلى المحتوى':'Skip to content';
 const nav=Object.entries(u.nav).filter(([id])=>id!=='contact').map(([id,label])=>`<a href="#${id}" data-nav="${id}">${esc(label)}</a>`).join('');
 $('#desktopNav').innerHTML=nav;$('#mobileNav').innerHTML=nav+`<a href="#contact">${esc(u.contact)}</a>`;
 $$('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===language)));
 $('#app').innerHTML=`
 <section class="hero" id="home"><div class="container"><div class="hero-grid">
  <div class="hero-copy reveal"><div class="eyebrow">${esc(u.eyebrow)}</div><h1 class="hero-name"><span>${esc(d.first)}</span> <span>${esc(d.last)}</span></h1><p class="hero-position">${esc(u.shortPosition)}</p><p class="hero-intro">${esc(d.intro)}</p><div class="hero-tags">${d.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="hero-ctas"><a class="button primary" href="#projects">${esc(u.projectCTA)}${icon('arrow','direction-arrow')}</a><a class="button secondary" href="#experience">${esc(d.cta1)}</a>${pdfLink(language,u.download,'ghost')}</div><div class="hero-contact"><a href="mailto:ahshcompany@gmail.com">${icon('mail')}<span>ahshcompany@gmail.com</span></a><a href="tel:+966532013487">${icon('phone')}<span>+966 53 201 3487</span></a><a href="https://www.linkedin.com/in/ahmedpq" target="_blank" rel="noopener noreferrer">${icon('linkedin')}<span>LinkedIn</span></a></div></div>
  <div class="hero-visual reveal"><div class="portrait-frame"><img src="assets/ahmed-bukhari.webp" width="2048" height="1536" alt="${esc(u.originalPortrait)}" fetchpriority="high"><span class="portrait-label" dir="ltr">EXECUTIVE PROFILE · AB</span></div><div class="current-role"><small><i></i>${esc(d.nowK)}</small><strong>${esc(d.nowR)}</strong><span>${esc(d.nowO)}</span></div></div>
 </div><div class="hero-bottom"><span>${icon('location')}${esc(u.location)}</span><a class="scroll-cue" href="#projects">${esc(u.scroll)}${icon('down')}</a></div></div></section>
 <section class="snapshot" aria-label="${esc(u.profile)}"><div class="container snapshot-grid">${d.snap.slice(0,4).map(s=>`<div class="snapshot-item"><strong>${esc(s.t||s.n)}${s.plus?'+':''}</strong><small>${s.lbl}</small></div>`).join('')}</div></section>
 <section class="section projects-section" id="projects"><div class="container">${sectionHeader('01',d.pjK,u.projectsTitle,u.projectsIntro)}<div class="project-filter" role="group" aria-label="${esc(language==='ar'?'تصفية المشاريع':'Filter projects')}">${['all','policy','governance','operations'].map(k=>`<button class="filter-button" data-project-filter="${k}" aria-pressed="${k===projectFilter}">${esc(u[k])}</button>`).join('')}<span class="project-count" id="projectCount" role="status"></span></div>
 <article class="featured-project" data-project-item="modon" data-category="operations"><div><div class="feature-kicker"><span></span>${esc(u.feature)}</div>${organizationLogo("MDN")}<span class="project-context">${esc(m.ctx)}</span><h3>${esc(m.t)}</h3><p>${esc(m.d)}</p><div class="project-byline">${icon('role')}${esc(m.ctx2)}</div><div class="feature-stats"><div><strong>7</strong><span>${esc(m.s1)}</span></div><div><strong>35</strong><span>${esc(m.s2)}</span></div><div><strong>1</strong><span>${esc(m.s3)}</span></div></div><button class="detail-link" data-open-project="modon" aria-label="${esc(u.details+' - '+m.t)}">${esc(u.details)}${icon('arrow','direction-arrow')}</button></div><div class="feature-art">${hub()}</div><div class="project-areas">${m.areas.map(a=>`<span>${esc(a)}</span>`).join('')}</div></article>
 <div class="project-grid">${projectOrder.slice(1).map(projectCard).join('')}</div></div></section>
 <section class="section expertise-section" id="expertise"><div class="container">${sectionHeader('02',d.exK,u.skillsTitle,u.skillsIntro)}<div class="expertise-grid">${d.ex.map((e,i)=>`<details class="expertise-item" ${i===0?'open':''}><summary><span class="expertise-icon">${icon3d(e.ic)}</span><h3>${esc(e.t)}</h3><span class="plus" aria-hidden="true">+</span></summary><div class="expertise-detail"><p>${esc(e.d)}</p>${e.rel.map(r=>`<span>${esc(r)}</span>`).join('')}</div></details>`).join('')}</div><div class="skills-row"><div><h3>${esc(u.coreSkills)}</h3><p>${esc(u.coreSkillsDesc)}</p></div><div class="skills-content">${[...d.caps[0].i,...d.caps[4].i].map(s=>`<span>${esc(s)}</span>`).join('')}</div></div></div></section>
 <section class="section about-section" id="about"><div class="container about-grid"><div><div class="section-number"><span>03</span><span>${esc(d.aboutK)}</span></div><p class="about-lead">${esc(d.aboutLead)}</p></div><div class="about-body"><p>${esc(d.about1)}</p><p>${esc(d.about2)}</p><div class="vision-row"><strong>2030</strong><p>${d.vision}</p></div></div></div></section>
 <section class="section" id="experience"><div class="container">${sectionHeader('04',d.tlK,esc(d.tlH),d.tlP)}<div class="timeline"><div class="timeline-aside"><span class="since">2016</span><p>${esc(u.careerSince)}</p></div><div class="career-list">${d.jobs.map((j,i)=>`<details class="career-item" ${i===0?'open':''}><summary><span class="career-date">${j.when?j.when.map(esc).join(' - '):esc(j.city)}</span><div class="career-main">${organizationLogo(["MHRSD","SAC","SDC","ATL","DVT","AFC","BTM","NTP"][i])}<h3>${esc(j.org)}</h3><p>${esc(j.roles[0][0])}</p><div class="role-meta">${j.now?`<span>${esc(d.nowTag)}</span>`:''}${j.free?`<span>${esc(d.freeTag)}</span>`:''}<small>${esc(j.city)}</small></div></div>${icon('chevron','career-chevron')}</summary><div class="career-details">${j.roles.map(r=>`<div class="role-line"><strong>${esc(r[0])}</strong>${r[1]?`<small>${esc(r[1])}</small>`:''}</div>`).join('')}${j.note?`<p>${j.note}</p>`:''}${j.link?`<a class="detail-link" href="#projects">${esc(d.seeProj)}${icon('arrow','direction-arrow')}</a>`:''}</div></details>`).join('')}</div></div></div></section>
 <section class="section credentials-section" id="credentials"><div class="container">${sectionHeader('05',u.credentialsLabel,u.credentialsTitle,u.certIntro)}<div class="education-grid">${d.edu.map((e,i)=>`<article class="education-card"><div class="university-identity">${universityImage(i,e.u)}</div><div class="education-content"><strong>${esc(e.deg)}</strong><h3>${esc(e.f)}</h3><p>${esc(e.u)}</p><small>${esc(e.y)}</small></div></article>`).join('')}</div><div class="cert-heading"><h3>${esc(d.ceK)}</h3><span id="certCount" role="status"></span></div><div class="project-filter" role="group" aria-label="${esc(d.ceP)}"><button class="filter-button" data-cert-filter="all" aria-pressed="${certificateFilter==='all'}">${esc(d.ceAll)}</button>${Object.entries(d.cats).map(([k,v])=>`<button class="filter-button" data-cert-filter="${k}" aria-pressed="${certificateFilter===k}">${esc(v)}</button>`).join('')}</div><div class="certificate-grid" id="certificates"></div>
 <details class="standards"><summary><span>${esc(d.stK)}</span>${icon('chevron')}</summary><div class="standards-grid">${d.std.map(([code,label])=>`<div class="standard"><strong>${esc(code)}</strong><small>${esc(label)}</small></div>`).join('')}</div></details><details class="standards"><summary><span>${esc(d.trH)}</span>${icon('chevron')}</summary><div class="training-tags">${d.train.map(t=>`<span>${esc(t)}</span>`).join('')}</div></details></div></section>
 <section class="section organizations-section" id="organizations"><div class="container">${sectionHeader('06',d.orK,esc(u.organizationsTitle),u.organizationsIntro)}<div class="organizations-grid">${d.orgs.map(([abbr,name,city,relation])=>`<div class="organization">${organizationLogo(abbr)}<div><strong>${esc(name)}</strong><small>${esc(d.rel[relation])} · ${esc(city)}</small></div></div>`).join('')}</div><div class="languages-row">${icon('globe')}<strong>${esc(d.lgH)}</strong>${d.langs.map(a=>`<span>${esc(a[0])}</span>`).join('')}</div></div></section>
 <section class="section contact-section" id="contact"><div class="container contact-grid"><div><div class="section-number"><span>07</span><span>${esc(d.coK)}</span></div><h2>${u.contactTitle}</h2><p>${esc(d.coP)}</p></div><div class="contact-links">${d.ct.slice(0,3).map(([label,value,href],i)=>`<div class="contact-row">${icon(['mail','phone','linkedin'][i])}<a href="${esc(href)}" ${i===2?'target="_blank" rel="noopener noreferrer"':''}><small>${esc(label)}</small><strong>${esc(value)}</strong></a>${i<2?`<button data-copy="${esc(value)}" aria-label="${esc(i===0?u.copyEmail:u.copyPhone)}">${icon('copy')}</button>`:icon('external','out-arrow')}</div>`).join('')}</div></div></section>
 <section class="section device-section" id="cv"><div class="container">${sectionHeader('08',d.dvK,u.deviceTitle,u.deviceIntro)}<div class="cv-actions">${pdfLink(language,language==='ar'?u.cvArabic:u.cvEnglish,'primary')}${pdfLink(language==='ar'?'en':'ar',language==='ar'?u.cvEnglish:u.cvArabic)}</div><div class="device-stage"><div class="monitor"><a class="monitor-screen device-live" href="#home" aria-label="${language==='ar'?'العودة إلى واجهة الموقع':'Go to website home'}"><div class="mini-nav"><img src="assets/ahmed-bukhari-final-symbol.svg" alt=""><b>${esc(d.name)}</b><span>${esc(d.pjK)} · ${esc(d.exK)} · ${esc(d.coK)}</span></div><div class="mini-hero" dir="${language==='ar'?'rtl':'ltr'}"><div><small>${esc(u.eyebrow)}</small><h3>${esc(d.name)}</h3><p>${esc(u.shortPosition)}</p><div class="mini-focus-tags"><span>GRC</span><span>PMP</span><span>ISO</span></div><span class="mini-button">${esc(u.projectCTA)} ↗</span></div><img class="mini-portrait" src="assets/ahmed-bukhari.webp" alt=""></div><div class="mini-categories">${['grc','pm','analytics'].map((n,i)=>`<div>${icon3d(n)}<span>${esc([u.governance,language==='ar'?'إدارة المشاريع':'Project management',language==='ar'?'التميّز التشغيلي':'Operational excellence'][i])}</span></div>`).join('')}</div><div class="mini-summary" dir="${language==='ar'?'rtl':'ltr'}"><div><strong>06</strong><span>${language==='ar'?'مشاريع مختارة':'Selected projects'}</span></div><div><strong>13</strong><span>${language==='ar'?'شهادة مهنية':'Professional credentials'}</span></div><div><strong>MBA</strong><span>${language==='ar'?'إدارة الأعمال':'Business administration'}</span></div></div></a><div class="monitor-neck"></div><div class="monitor-foot"></div></div><a class="tablet" href="${assetURL(`Ahmed_Bukhari_CV_Updated_${language.toUpperCase()}.pdf`)}" target="_blank" rel="noopener" aria-label="${language==='ar'?'افتح السيرة الذاتية':'Open CV'}"><img src="${assetURL(`assets/cvthumb_${language}.png`)}" alt="${language==='ar'?'معاينة السيرة الذاتية الجديدة':'Updated CV preview'}" loading="lazy"><span class="device-hint">PDF · 2 ${language==='ar'?'صفحات':'pages'}</span></a><a class="phone device-live" href="#contact" aria-label="${esc(u.contact)}"><div class="mini-phone" dir="${language==='ar'?'rtl':'ltr'}"><img class="mini-phone-logo" src="assets/ahmed-bukhari-final-symbol.svg" alt=""><img class="mini-phone-portrait" src="assets/ahmed-bukhari.webp" alt=""><h3>${esc(d.name)}</h3><p>${esc(u.shortPosition)}</p><div class="mini-phone-icons">${icon3d('grc')}${icon3d('qual')}</div><span class="mini-button">${esc(u.contact)} ↗</span></div></a></div><p class="device-caption">${esc(u.deviceCaption)}</p></div></section>`;
 closeMenu();filterProjects();renderCertificates();trackSections();revealSections();setupInteractions();
}
function revealSections(){
 if(revealObserver)revealObserver.disconnect();
 if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;
 revealObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.classList.add('scroll-enter');revealObserver.unobserve(entry.target);}}},{threshold:.12});
 $$('.section-header,.project-card,.expertise-item,.education-card').forEach(el=>revealObserver.observe(el));
}
function filterProjects(){let visible=0;$$('[data-project-item]').forEach(p=>{const show=projectFilter==='all'||p.dataset.category===projectFilter;p.hidden=!show;if(show)visible++;});$$('[data-project-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.projectFilter===projectFilter)));$('#projectCount').textContent=UI[language].filterResult(visible);}

function localVisual(path,alt,cls){const src=typeof EMBEDDED_ASSETS!=='undefined'?(EMBEDDED_ASSETS[path]||path):path;return `<img class="${cls}" src="${src}" alt="${esc(alt)}" loading="eager" decoding="async">`;}
function universityImage(i,alt){return localVisual(i===0?'assets/credentials/seu-supplied-display.svg':'assets/credentials/kfupm.svg',alt,'university-logo');}
function credentialVisual(name,family){
 if(name==="ISO 31000 RM Lead Auditor")name="ISO 31000 Risk Manager";
 const suppliedBadges={"Lean Six Sigma Yellow Belt": "assets/credentials/sigma-yellow-transparent.png", "Lean Six Sigma Master Black Belt": "assets/credentials/sigma-master-black-transparent.png", "Lean Six Sigma Green Belt": "assets/credentials/sigma-green-transparent.png", "Lean Six Sigma Black Belt": "assets/credentials/sigma-black-transparent.png", "ISO 9001 QMS Lead Auditor": "assets/credentials/pecb-9001-transparent.png", "Total Quality Management": "assets/credentials/tqm-supplied.png", "ISO 31000 Risk Manager": "assets/credentials/pecb-31000-transparent.png", "ISO 22301 BCMS Lead Auditor": "assets/credentials/pecb-22301-display.svg", "ISO 45001 OH&S Lead Auditor": "assets/credentials/pecb-45001-display.svg", "ISO 22000 FSMS Lead Auditor": "assets/credentials/pecb-22000-display.svg"};
 if(suppliedBadges[name])return `<div class="credential-image supplied-badge-image ${name.startsWith('Lean Six Sigma')?'belt-transparent':''}">${localVisual(suppliedBadges[name],name,"credential-logo")}</div>`;
 if(name==='PMP')return `<div class="credential-image pmp-image">${localVisual('assets/credentials/pmp.png','PMP - Project Management Institute','credential-logo')}</div>`;
 if(family==='grc'){const key=name.includes('Auditor')?'grca':'grcp';return `<div class="credential-image grc-mark-image">${localVisual('assets/credentials/'+key+'-supplied-display.svg',key.toUpperCase()+' - OCEG','credential-logo')}</div>`;}
 return '';
}

function renderCertificates(){const d=D[language],items=CERTS.filter(c=>certificateFilter==='all'||c[1]===certificateFilter);$('#certificates').innerHTML=items.map(([name,family])=>`<article class="certificate">${credentialVisual(name,family)}<div><small>${esc(d.cats[family])}</small><strong>${esc(language==='ar'?(d.certAr[name]||name):name)}</strong></div></article>`).join('');$('#certCount').textContent=UI[language].certResult(items.length);$$('[data-cert-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.certFilter===certificateFilter)));}
function closeMenu(){const b=$('#menuButton');$('#mobileNav').hidden=true;b.setAttribute('aria-expanded','false');b.ariaLabel=UI[language].openMenu;}
function toggleMenu(){const b=$('#menuButton'),open=b.getAttribute('aria-expanded')!=='true';$('#mobileNav').hidden=!open;b.setAttribute('aria-expanded',String(open));b.ariaLabel=open?UI[language].closeMenu:UI[language].openMenu;}
function openProject(key){const d=D[language],u=UI[language],p=d[key];if(!projectOrder.includes(key))return;const scope=key==='modon'?p.areas:p.tags;$('#dialogContent').innerHTML=`<div class="dialog-visual">${key==='modon'?diagram('epm'):diagram(p.g)}</div><div class="dialog-body">${projectOrganization(key)}<span class="project-context">${esc(p.ctx)}</span><h2 id="dialogTitle">${esc(p.t)}</h2>${p.role?`<span class="dialog-role">${esc(u.role)} · ${esc(p.role)}</span>`:''}<p>${esc(p.d)}</p>${key==='modon'?`<div class="project-byline">${esc(p.ctx2)}</div>`:''}<div class="dialog-scope"><h3>${esc(key==='modon'?u.scopeMODON:u.scope)}</h3><div class="chips">${scope.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div><div class="dialog-foot"><span>${esc(d.name)}</span><a href="#contact" data-dialog-contact>${esc(u.modalContact)}${icon('arrow','direction-arrow')}</a></div></div>`;$('#projectDialog').showModal();document.body.style.overflow='hidden';$('#closeDialog').focus();}
function closeProject(){if($('#projectDialog').open)$('#projectDialog').close();document.body.style.overflow='';}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3000);}
async function copyContact(value){try{await navigator.clipboard.writeText(value);toast(D[language].copied);}catch(_){toast(UI[language].copyError);}}
function trackSections(){
 if(observer)observer.disconnect();
 requestAnimationFrame(updateScrollExperience);
}
function scrollState(tops, focus){let active=-1;for(let i=0;i<tops.length;i++){if(tops[i]<=focus)active=i;}return active;}
function updateScrollExperience(){
 const header=$('#siteHeader');const focus=Math.max((header?.offsetHeight||80)+35,innerHeight*.42);
 const sections=$$('main>section[id]');
 let idx=scrollState(sections.map(s=>s.getBoundingClientRect().top),Math.max((header?.offsetHeight||80)+35,innerHeight*.25));
 if(sections.length){idx=Math.max(0,idx);activeSection=sections[idx].id;
 $$('[data-nav]').forEach(a=>{const on=a.dataset.nav===activeSection;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});
 sections.forEach((s,i)=>s.classList.toggle('section-current',i===idx));}
 const list=$('.career-list');const items=$$('.career-item');
 if(list&&items.length){
  const rect=list.getBoundingClientRect();const points=items.map(e=>e.getBoundingClientRect().top+18);
  const active=scrollState(points,focus);const first=points[0]-rect.top;const last=points[points.length-1]-rect.top;
  const fill=Math.max(0,Math.min(last-first,focus-rect.top-first));
  list.style.setProperty('--track-start',first+'px');list.style.setProperty('--track-length',Math.max(0,last-first)+'px');list.style.setProperty('--track-fill',fill+'px');
  items.forEach((e,i)=>{e.classList.toggle('career-passed',i<active);e.classList.toggle('career-current',i===active);const summary=$('summary',e);if(i===active)summary.setAttribute('aria-current','step');else summary.removeAttribute('aria-current');});
  const current=items[Math.max(0,active)];const label=$('.career-live-label');if(label)label.textContent=$('.career-main h3',current).textContent;
  const count=$('.career-live-count');if(count)count.textContent=`${Math.max(0,active)+1} / ${items.length}`;
 }
 header?.classList.toggle('is-scrolled',window.scrollY>20);
 const top=$('#backTop');if(top)top.classList.toggle('backtop-ready',window.scrollY>400);
}
function setupInteractions(){
 const aside=$('.timeline-aside');if(aside&&!$('.career-controls',aside)){aside.insertAdjacentHTML('beforeend',`<div class="career-controls"><span class="career-live-label"></span><div><button type="button" data-career-step="-1" aria-label="${language==='ar'?'الخبرة السابقة':'Previous role'}">${icon('up')}</button><span class="career-live-count"></span><button type="button" data-career-step="1" aria-label="${language==='ar'?'الخبرة التالية':'Next role'}">${icon('down')}</button></div></div>`);}
 requestAnimationFrame(updateScrollExperience);
}

document.addEventListener('click',e=>{
 const b=e.target.closest('button');
 if(b?.dataset.lang&&b.dataset.lang!==language){const section=activeSection;closeProject();language=b.dataset.lang;try{localStorage.setItem('ahmed-profile-language',language);}catch(_){}render();const target=document.getElementById(section);if(window.scrollY>200&&target)target.scrollIntoView({behavior:'instant',block:'start'});}
 else if(b?.dataset.projectFilter){projectFilter=b.dataset.projectFilter;filterProjects();}
 else if(b?.dataset.certFilter){certificateFilter=b.dataset.certFilter;renderCertificates();}
 else if(b?.dataset.openProject){openProject(b.dataset.openProject);}
 else if(b?.dataset.copy){copyContact(b.dataset.copy);}
 const link=e.target.closest('a[href^="#"]');if(link){closeMenu();if(link.hasAttribute('data-dialog-contact'))closeProject();}
});
$('#menuButton').addEventListener('click',toggleMenu);$('#closeDialog').addEventListener('click',closeProject);$('#projectDialog').addEventListener('close',()=>document.body.style.overflow='');$('#projectDialog').addEventListener('click',e=>{if(e.target===$('#projectDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeProject();}});$('#backTop').addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();}});
let scrollQueued=false;window.addEventListener('scroll',()=>{if(scrollQueued)return;scrollQueued=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;updateScrollExperience();$('#scrollProgress').style.width=`${max>0?(window.scrollY/max)*100:0}%`;scrollQueued=false;});},{passive:true});window.addEventListener('resize',()=>{if(innerWidth>1000)closeMenu();requestAnimationFrame(updateScrollExperience);});
render();
document.documentElement.classList.add("app-ready");

document.addEventListener('toggle',e=>{if(e.target.matches('.career-item,.expertise-item,.standards'))requestAnimationFrame(updateScrollExperience);},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-career-step]');if(!b)return;const items=$$('.career-item');let i=items.findIndex(x=>x.classList.contains('career-current'));if(i<0)i=0;i=Math.max(0,Math.min(items.length-1,i+Number(b.dataset.careerStep)));const y=items[i].getBoundingClientRect().top+scrollY-innerHeight*.42+18;window.scrollTo({top:Math.max(0,y),behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});});
window.addEventListener('load',updateScrollExperience);
if(document.fonts)document.fonts.ready.then(updateScrollExperience);

function assetURL(path){return typeof EMBEDDED_ASSETS!=="undefined"?(EMBEDDED_ASSETS[path]||path):path;}
