// Professional facts retained from the supplied profile.
const D = {
en:{
  mono:"AB", name:"Ahmed Bukhari", first:"Ahmed", last:"Bukhari",
  nav:[["home","Home"],["about","About"],["expertise","Expertise"],["projects","Projects"],["experience","Experience"],["credentials","Credentials"],["contact","Contact"]],
  loc:"Riyadh, Saudi Arabia",
  pos:"Quality, GRC & Operational Excellence Leader",
  tags:["Chemical Engineer","MBA","PMP","GRC","Quality & Compliance"],
  intro:"Management consultancy and quality professional working across quality management, governance, risk and compliance, operational excellence, business process improvement and health & safety.",
  cta1:"Explore experience", cta2:"View projects", cta3:"Download CV",
  nowK:"Current role", nowR:"Work Environment Policies Director", nowO:"Ministry of Human Resources and Social Development",
  monoCap:"Portrait",
  disc:["Quality Management","Governance, Risk & Compliance","Operational Excellence","Business Process Improvement","Management Consultancy","Health & Safety"],
  snap:[
    {n:2016,lbl:"<b>Experience since</b>Professional career start"},
    {t:"MBA",lbl:"<b>Master of Business Administration</b>Saudi Electronic University"},
    {t:"B.Sc.",lbl:"<b>Chemical Engineering</b>King Fahd University of Petroleum & Minerals"},
    {n:13,plus:true,lbl:"<b>Professional certifications</b>GRC, PMP, Lean Six Sigma, ISO"},
    {focus:["Quality","GRC","Risk","Compliance","Operational Excellence"],lbl:"<b>Core focus</b>"}
  ],
  aboutK:"About Ahmed",
  aboutLead:"An engineer by training who moved from the plant floor into quality, consulting and governance, and now shapes policy at ministry level.",
  about1:"Ahmed Bukhari is a management consultancy and quality professional with experience across quality, compliance, risk, business processes, governance, operational excellence and health & safety management. He works effectively in high-pressure, complex environments, from a government ministry and a PIF company to consulting assignments that spanned MODON's headquarters and 35 industrial cities.",
  about2:"His path runs from process and quality control engineering, through regional quality assurance auditing and management consultancy, to GRC advisory and director-level roles at the Ministry of Human Resources and Social Development.",
  vision:"<b>Professional objective.</b> To apply his experience in quality, governance and operational excellence in contributing to Saudi Vision 2030.",
  exK:"Areas of expertise", exH:"Six disciplines, one operating view", exP:"How Ahmed's work is organized across governance, quality and delivery. Select an area to see what it covers.",
  ex:[
    {ic:"grc",t:"Governance, Risk & Compliance",d:"GRC frameworks, compliance management systems, audits, governance structures and risk management.",rel:["Certified GRCP Professional","Certified GRCA Auditor","ISO 37301","ISO 31000"]},
    {ic:"qual",t:"Quality & Operational Excellence",d:"Quality management systems, continuous improvement, KPIs, Lean, Six Sigma and organizational excellence.",rel:["Total Quality Management","Lean Six Sigma Master Black Belt","EFQM","King Abdulaziz Quality Award"]},
    {ic:"iso",t:"Management Systems & ISO",d:"ISO 9001, ISO 37301, ISO 45001, ISO 22301, ISO 31000 and related management systems.",rel:["ISO 9001","ISO 45001","ISO 22301","ISO 56002","ISO 10002","ISO 10004"]},
    {ic:"bpm",t:"Business Process Management",d:"Policies, procedures, process development, SLA development and enterprise process management.",rel:["Enterprise Process Management, Soudah Development"]},
    {ic:"pm",t:"Project Management",d:"PMP-based project leadership, transformation programs and cross-functional initiatives.",rel:["PMP","Compliance Management System & Program","ATLAS restructuring"]},
    {ic:"aud",t:"Audit & Assessment",d:"Internal auditing, conformity assessment, accreditation and compliance auditing.",rel:["Saudi Accreditation Center","ISO 17020","Lead Auditor credentials"]}
  ],
  relL:"Related in Ahmed's record",
  pjK:"Selected projects", pjH:"Work at national and enterprise scale", pjP:"Six engagements from Ahmed's CV, from national labor reform to management systems across MODON's industrial cities.",
  swipe:"Swipe to see more projects",
  pj1:{ctx:"Ministry of Human Resources and Social Development",t:"Reforming the Saudi Labor System",role:"Ministerial Committee Member",d:"Member of the ministerial committee for reforming the Saudi labor system, representing the Ministry of Human Resources and Social Development.",tags:["National policy","Labor system"],g:"law"},
  pj2:{ctx:"Governance and compliance",t:"Compliance Management System & Compliance Program",role:"Project Manager",d:"Managed the project to establish a compliance management system together with the compliance program that puts it into practice.",tags:["Compliance management","Governance"],g:"cms"},
  modon:{ctx:"Saudi Authority for Industrial Cities and Technology Zones (MODON)",ctx2:"Consulting assignment with DEVOTEAM",t:"MODON management systems transformation",role:"Managed and implemented",d:"Seven management systems projects alongside the quality culture project, covering MODON's headquarters and its 35 industrial cities.",s1:"Management systems projects",s2:"Industrial cities, plus the headquarters",s3:"Quality culture project",areas:["Quality","Customer satisfaction","Occupational health & safety","Innovation","Business continuity","Risk","Integrated management"],hq:"MODON",hqs:"Headquarters",lg1:"Headquarters",lg2:"35 industrial cities",cap:"MODON headquarters connected to its 35 industrial cities"},
  pj4:{ctx:"Soudah Development Company (PIF)",t:"Enterprise Process Management",role:"Managed and implemented",d:"An enterprise process management initiative covering policies, procedures and business processes.",tags:["Policies","Procedures","Business processes"],g:"epm"},
  pj5:{ctx:"Soudah Development Company (PIF)",t:"Soudah Development governance in Oracle",role:null,d:"Reflecting Soudah Development's governance within the Oracle system.",tags:["Governance","Oracle"],g:"gov"},
  pj6:{ctx:"ATLAS, freelance engagement",t:"ATLAS company restructuring",role:"Project Manager",d:"Project manager for the restructuring of ATLAS company, January to February 2021.",tags:["Restructuring"],g:"rst"},
  tlK:"Career journey", tlH:"From process engineering to policy leadership", tlP:"Roles in reverse order. Open any position to see its titles, dates and related work.",
  nowTag:"Current", freeTag:"Freelance", details:"Details", seeProj:"See related project",
  jobs:[
    {org:"Ministry of Human Resources and Social Development",city:"Riyadh",when:["Mar 2023","Present"],now:true,roles:[["Work Environment Policies Director","Mar 2023 – Present"],["Quality Director (Acting)","Mar 2023 – Present"]],note:"<b>Ministerial Committee Member</b> for reforming the Saudi labor system.",link:"projects"},
    {org:"Saudi Accreditation Center",city:"Riyadh",when:["Sep 2022","Present"],now:true,free:true,roles:[["Expert / Assessor","Sep 2022 – Present"]],note:"Freelance expert and assessor engagement."},
    {org:"Soudah Development Company (PIF)",city:"Riyadh",when:["Jun 2021","Mar 2023"],roles:[["Senior Quality, Compliance & Accreditation Officer","Jun 2021 – Mar 2023"],["GRC Advisor","Sep 2021 – May 2022"]],note:"Projects: <b>enterprise process management</b> (policies, procedures, business processes) and <b>reflecting SD governance in the Oracle system</b>.",link:"projects"},
    {org:"ATLAS",city:"Riyadh",when:["Jan 2021","Feb 2021"],free:true,roles:[["Project Manager","Jan 2021 – Feb 2021"]],note:"ATLAS company restructuring."},
    {org:"DEVOTEAM",city:"Riyadh",when:["Jan 2019","May 2021"],roles:[["Senior Consultant","Apr 2021 – May 2021"],["Consultant","Jan 2019 – Apr 2021"]],note:"<b>MODON assignment:</b> managed and implemented 7 management systems projects and the quality culture project across the headquarters and 35 industrial cities.",link:"projects"},
    {org:"Arrow Food Co.",city:"Dammam",when:["Apr 2017","Jan 2019"],roles:[["Regional Quality Assurance Auditor, East & North Province","Apr 2017 – Jan 2019"]]},
    {org:"BITUMAT",city:"Dammam",when:["Oct 2016","Mar 2017"],roles:[["QC Engineer","Oct 2016 – Mar 2017"]]},
    {org:"NATPET",city:"Yanbu",when:null,roles:[["Process Engineer",""]]}
  ],
  edK:"Education", edH:"Academic credentials",
  edu:[{deg:"MBA",f:"Master of Business Administration",u:"Saudi Electronic University, Riyadh",y:"2022 – 2024"},{deg:"B.Sc.",f:"Chemical Engineering",u:"King Fahd University of Petroleum & Minerals, Dhahran",y:"2010 – 2016"}],
  ceK:"Professional certifications", ceH:"A credential portfolio in five families", ceP:"Filter the certifications by family.",
  ceAll:"All", ceNote:"Issuing bodies and dates are not listed in the CV, so they are not shown here.",
  cats:{grc:"GRC",pm:"Project management",lss:"Lean Six Sigma",tqm:"Quality",iso:"ISO lead auditor"},
  caK:"Professional capabilities", caH:"Capabilities by area",
  caps:[
    {ic:"qual",t:"Quality & Excellence",i:["Total Quality Management","Six Sigma","Lean","7 Waste methodology","Quality tools","Quality management systems"]},
    {ic:"grc",t:"Governance & Compliance",i:["Compliance management systems","Audit","GRC","Risk management"]},
    {ic:"cx",t:"Customer Experience",i:["Customer complaints handling","Customer satisfaction measurement & monitoring"]},
    {ic:"iso",t:"Management Systems",i:["Occupational health & safety","Business continuity","Innovation management"]},
    {ic:"lead",t:"Leadership",i:["Leadership","Decision making","Problem solving","Training","Communication","Multitasking","Teamwork"]}
  ],
  stK:"Standards & frameworks", stH:"International standards in Ahmed's work", stP:"Standards and excellence frameworks documented in his CV.",
  std:[["ISO 9001","Quality management"],["ISO 10002","Customer complaints handling"],["ISO 10004","Customer satisfaction monitoring"],["ISO 45001","Occupational health & safety"],["ISO 56002","Innovation management"],["ISO 22301","Business continuity"],["ISO 31000","Risk management"],["ISO 37301","Compliance management"],["ISO 14001","Environmental management"],["ISO 17020","Conformity assessment, inspection bodies"],["EFQM","Excellence model"],["KAQA","King Abdulaziz Quality Award"]],
  stPre:"Standard", stFw:"Framework", stAw:"Award",
  trH:"Training & continuous development", trP:"Programs listed in the CV. Select to expand.",
  train:["Organizational Excellence","Crisis & Risk Management","Strategic Planning","Executive Leadership","Change Management","EFQM","KAQA","Risk Management","ISO standards"],
  orK:"Organizations & professional experience", orH:"Where Ahmed has worked", orP:"Each organization is labeled by its relationship to Ahmed, as stated in the CV.",
  rel:{emp:"Employer",free:"Freelance",client:"Client assignment"},
  orgs:[
    ["MHRSD","Ministry of Human Resources and Social Development","Riyadh","emp"],
    ["SAC","Saudi Accreditation Center","Riyadh","free"],
    ["SDC","Soudah Development Company (PIF)","Riyadh","emp"],
    ["DVT","DEVOTEAM","Riyadh","emp"],
    ["MDN","MODON, Saudi Authority for Industrial Cities and Technology Zones","Via DEVOTEAM","client"],
    ["AFC","Arrow Food Co.","Dammam","emp"],
    ["BTM","BITUMAT","Dammam","emp"],
    ["ATL","ATLAS","Riyadh","free"],
    ["NTP","NATPET","Yanbu","emp"]
  ],
  lgH:"Languages", langs:[["Arabic","العربية"],["English","الإنجليزية"]],
  dvK:"CV and digital profile", dvH:"The same profile on every screen", dvP:"This profile reads the same on desktop, tablet and phone. The full CV is available as a two-page A4 PDF in English and Arabic.",
  dvB:"Download full CV", dvB2:"Arabic CV", dvS:"PDF, A4, two pages.",
  coK:"Contact", coH:"Let's connect", coP:"Based in Riyadh, Saudi Arabia. Reach Ahmed directly by email, phone or LinkedIn.",
  ct:[["Email","ahshcompany@gmail.com","mailto:ahshcompany@gmail.com"],["Phone","+966 53 201 3487","tel:+966532013487"],["LinkedIn","linkedin.com/in/ahmedpq","https://www.linkedin.com/in/ahmedpq"],["Location","Riyadh, Saudi Arabia",null]],
  foot:"© Ahmed Bukhari. Executive profile.", top:"Back to top",
  copied:"Copied to clipboard.", copy:"Copy", dlOk:"CV download started.", dlNo:"Download was cancelled.", dlErr:"The CV couldn't be saved here. Try again from the published page."
},
ar:{
  mono:"أ ب", name:"أحمد بخاري", first:"أحمد", last:"بخاري",
  nav:[["home","الرئيسية"],["about","نبذة"],["expertise","الخبرات"],["projects","المشاريع"],["experience","المسيرة"],["credentials","الشهادات"],["contact","التواصل"]],
  loc:"الرياض، المملكة العربية السعودية",
  pos:"قيادي في الجودة والحوكمة والمخاطر والالتزام والتميّز التشغيلي",
  tags:["مهندس كيميائي","ماجستير إدارة أعمال","PMP","الحوكمة والمخاطر والالتزام","الجودة والامتثال"],
  intro:"مختص في الاستشارات الإدارية والجودة، يعمل في مجالات إدارة الجودة، والحوكمة والمخاطر والالتزام، والتميّز التشغيلي، وتحسين إجراءات الأعمال، والصحة والسلامة.",
  cta1:"استعرض المسيرة", cta2:"المشاريع", cta3:"تحميل السيرة الذاتية",
  nowK:"المنصب الحالي", nowR:"مدير سياسات بيئة العمل", nowO:"وزارة الموارد البشرية والتنمية الاجتماعية",
  monoCap:"الصورة الشخصية",
  disc:["إدارة الجودة","الحوكمة والمخاطر والالتزام","التميّز التشغيلي","تحسين إجراءات الأعمال","الاستشارات الإدارية","الصحة والسلامة"],
  snap:[
    {n:2016,lbl:"<b>في الميدان المهني منذ</b>بداية المسيرة المهنية"},
    {t:"MBA",lbl:"<b>ماجستير إدارة الأعمال</b>الجامعة السعودية الإلكترونية"},
    {t:"B.Sc.",lbl:"<b>بكالوريوس الهندسة الكيميائية</b>جامعة الملك فهد للبترول والمعادن"},
    {n:13,plus:true,lbl:"<b>شهادة مهنية</b>الحوكمة، PMP، لين سيجما ستة، ISO"},
    {focus:["الجودة","الحوكمة","المخاطر","الالتزام","التميّز التشغيلي"],lbl:"<b>محاور التركيز</b>"}
  ],
  aboutK:"نبذة عن أحمد",
  aboutLead:"مهندس في الأصل، انتقل من بيئة المصنع إلى الجودة والاستشارات والحوكمة، ويسهم اليوم في صياغة السياسات على مستوى الوزارة.",
  about1:"أحمد بخاري مختص في الاستشارات الإدارية والجودة، يمتلك خبرة في الجودة والالتزام والمخاطر وإجراءات الأعمال والحوكمة والتميّز التشغيلي وإدارة الصحة والسلامة. يعمل بكفاءة في بيئات العمل المعقدة وتحت الضغط، من وزارة حكومية وشركة تابعة لصندوق الاستثمارات العامة، إلى مهام استشارية شملت المقر الرئيس لهيئة «مدن» و35 مدينة صناعية.",
  about2:"تمتد مسيرته من هندسة العمليات ومراقبة الجودة، مرورًا بتدقيق ضمان الجودة على المستوى الإقليمي والاستشارات الإدارية، وصولًا إلى استشارات الحوكمة والمخاطر والالتزام ومناصب قيادية في وزارة الموارد البشرية والتنمية الاجتماعية.",
  vision:"<b>الهدف المهني:</b> توظيف خبرته في الجودة والحوكمة والتميّز التشغيلي في الإسهام في تحقيق رؤية المملكة 2030.",
  exK:"مجالات الخبرة", exH:"ستة مجالات برؤية تشغيلية واحدة", exP:"كيف تتوزع خبرات أحمد بين الحوكمة والجودة والتنفيذ. اختر مجالًا لعرض تفاصيله.",
  ex:[
    {ic:"grc",t:"الحوكمة والمخاطر والالتزام",d:"أطر الحوكمة والمخاطر والالتزام، وأنظمة إدارة الالتزام، والتدقيق، والهياكل الحوكمية، وإدارة المخاطر.",rel:["Certified GRCP Professional","Certified GRCA Auditor","ISO 37301","ISO 31000"]},
    {ic:"qual",t:"الجودة والتميّز التشغيلي",d:"أنظمة إدارة الجودة، والتحسين المستمر، ومؤشرات الأداء، والمنهجية الرشيقة، وسيجما ستة، والتميّز المؤسسي.",rel:["Total Quality Management","Lean Six Sigma Master Black Belt","EFQM","جائزة الملك عبدالعزيز للجودة"]},
    {ic:"iso",t:"أنظمة الإدارة ومعايير ISO",d:"ISO 9001 وISO 37301 وISO 45001 وISO 22301 وISO 31000 وما يتصل بها من أنظمة إدارة.",rel:["ISO 9001","ISO 45001","ISO 22301","ISO 56002","ISO 10002","ISO 10004"]},
    {ic:"bpm",t:"إدارة إجراءات الأعمال",d:"السياسات والإجراءات، وتطوير العمليات، وإعداد اتفاقيات مستوى الخدمة، وإدارة إجراءات المؤسسة.",rel:["إدارة إجراءات المؤسسة، تطوير السودة"]},
    {ic:"pm",t:"إدارة المشاريع",d:"قيادة المشاريع وفق منهجية PMP، وبرامج التحول، والمبادرات متعددة الإدارات.",rel:["PMP","نظام إدارة الالتزام وبرنامجه","إعادة هيكلة أطلس"]},
    {ic:"aud",t:"التدقيق والتقييم",d:"التدقيق الداخلي، وتقييم المطابقة، والاعتماد، وتدقيق الالتزام.",rel:["المركز السعودي للاعتماد","ISO 17020","شهادات المدقق الرئيس"]}
  ],
  relL:"ما يرتبط بها في سجل أحمد",
  pjK:"مشاريع مختارة", pjH:"أعمال على المستويين الوطني والمؤسسي", pjP:"ستة مشاريع من سيرة أحمد، من إصلاح نظام العمل على المستوى الوطني إلى أنظمة الإدارة في مدن «مدن» الصناعية.",
  swipe:"اسحب لعرض بقية المشاريع",
  pj1:{ctx:"وزارة الموارد البشرية والتنمية الاجتماعية",t:"إصلاح نظام العمل السعودي",role:"عضو اللجنة الوزارية",d:"عضو في اللجنة الوزارية لإصلاح نظام العمل السعودي، ممثلًا لوزارة الموارد البشرية والتنمية الاجتماعية.",tags:["سياسات وطنية","نظام العمل"],g:"law"},
  pj2:{ctx:"الحوكمة والالتزام",t:"نظام إدارة الالتزام وبرنامج الالتزام",role:"مدير المشروع",d:"إدارة مشروع إنشاء نظام لإدارة الالتزام، إلى جانب برنامج الالتزام الذي يضعه موضع التطبيق.",tags:["إدارة الالتزام","الحوكمة"],g:"cms"},
  modon:{ctx:"الهيئة السعودية للمدن الصناعية ومناطق التقنية «مدن»",ctx2:"مهمة استشارية ضمن ديفوتيم DEVOTEAM",t:"تحوّل أنظمة الإدارة في «مدن»",role:"إدارة وتطبيق",d:"سبعة مشاريع لأنظمة الإدارة إلى جانب مشروع ثقافة الجودة، شملت المقر الرئيس للهيئة و35 مدينة صناعية.",s1:"مشاريع لأنظمة الإدارة",s2:"مدينة صناعية، إضافة إلى المقر الرئيس",s3:"مشروع ثقافة الجودة",areas:["الجودة","رضا العملاء","الصحة والسلامة المهنية","الابتكار","استمرارية الأعمال","المخاطر","الإدارة المتكاملة"],hq:"مدن",hqs:"المقر الرئيس",lg1:"المقر الرئيس",lg2:"35 مدينة صناعية",cap:"المقر الرئيس لهيئة مدن مرتبطًا بمدنها الصناعية الـ35"},
  pj4:{ctx:"شركة تطوير السودة (صندوق الاستثمارات العامة)",t:"إدارة إجراءات المؤسسة",role:"إدارة وتطبيق",d:"مبادرة لإدارة إجراءات المؤسسة شملت السياسات والإجراءات وإجراءات الأعمال.",tags:["السياسات","الإجراءات","إجراءات الأعمال"],g:"epm"},
  pj5:{ctx:"شركة تطوير السودة (صندوق الاستثمارات العامة)",t:"حوكمة تطوير السودة في نظام أوراكل",role:null,d:"عكس حوكمة شركة تطوير السودة داخل نظام أوراكل.",tags:["الحوكمة","أوراكل Oracle"],g:"gov"},
  pj6:{ctx:"أطلس، عمل حر",t:"إعادة هيكلة شركة أطلس",role:"مدير المشروع",d:"مدير مشروع إعادة هيكلة شركة أطلس، من يناير إلى فبراير 2021.",tags:["إعادة الهيكلة"],g:"rst"},
  tlK:"المسيرة المهنية", tlH:"من هندسة العمليات إلى قيادة السياسات", tlP:"المناصب من الأحدث إلى الأقدم. افتح أي منصب لعرض المسميات والتواريخ والأعمال المرتبطة.",
  nowTag:"حاليًا", freeTag:"عمل حر", details:"التفاصيل", seeProj:"عرض المشروع المرتبط",
  jobs:[
    {org:"وزارة الموارد البشرية والتنمية الاجتماعية",city:"الرياض",when:["مارس 2023","حتى الآن"],now:true,roles:[["مدير سياسات بيئة العمل","مارس 2023 – حتى الآن"],["مدير الجودة (مكلّف)","مارس 2023 – حتى الآن"]],note:"<b>عضو اللجنة الوزارية</b> لإصلاح نظام العمل السعودي.",link:"projects"},
    {org:"المركز السعودي للاعتماد",city:"الرياض",when:["سبتمبر 2022","حتى الآن"],now:true,free:true,roles:[["خبير / مُقيِّم","سبتمبر 2022 – حتى الآن"]],note:"خبير ومُقيِّم بنظام العمل الحر."},
    {org:"شركة تطوير السودة (صندوق الاستثمارات العامة)",city:"الرياض",when:["يونيو 2021","مارس 2023"],roles:[["أخصائي أول الجودة والالتزام والاعتماد","يونيو 2021 – مارس 2023"],["مستشار الحوكمة والمخاطر والالتزام","سبتمبر 2021 – مايو 2022"]],note:"المشاريع: <b>إدارة إجراءات المؤسسة</b> (السياسات والإجراءات وإجراءات الأعمال)، و<b>عكس حوكمة الشركة في نظام أوراكل</b>.",link:"projects"},
    {org:"أطلس ATLAS",city:"الرياض",when:["يناير 2021","فبراير 2021"],free:true,roles:[["مدير مشروع","يناير 2021 – فبراير 2021"]],note:"إعادة هيكلة شركة أطلس."},
    {org:"ديفوتيم DEVOTEAM",city:"الرياض",when:["يناير 2019","مايو 2021"],roles:[["مستشار أول","أبريل 2021 – مايو 2021"],["مستشار","يناير 2019 – أبريل 2021"]],note:"<b>مهمة «مدن»:</b> إدارة وتطبيق 7 مشاريع لأنظمة الإدارة ومشروع ثقافة الجودة في المقر الرئيس و35 مدينة صناعية.",link:"projects"},
    {org:"شركة آرو للأغذية Arrow Food Co.",city:"الدمام",when:["أبريل 2017","يناير 2019"],roles:[["مدقق ضمان الجودة الإقليمي، المنطقتان الشرقية والشمالية","أبريل 2017 – يناير 2019"]]},
    {org:"بيتومات BITUMAT",city:"الدمام",when:["أكتوبر 2016","مارس 2017"],roles:[["مهندس مراقبة الجودة","أكتوبر 2016 – مارس 2017"]]},
    {org:"ناتبت NATPET",city:"ينبع",when:null,roles:[["مهندس عمليات",""]]}
  ],
  edK:"التعليم", edH:"المؤهلات الأكاديمية",
  edu:[{deg:"الماجستير",f:"ماجستير إدارة الأعمال MBA",u:"الجامعة السعودية الإلكترونية، الرياض",y:"2022 – 2024"},{deg:"البكالوريوس",f:"الهندسة الكيميائية",u:"جامعة الملك فهد للبترول والمعادن، الظهران",y:"2010 – 2016"}],
  ceK:"الشهادات المهنية", ceH:"شهادات مهنية في خمس فئات", ceP:"صفِّ الشهادات حسب الفئة.",
  ceAll:"الكل", ceNote:"لم تُذكر جهات الإصدار وتواريخها في السيرة الذاتية، لذا لا تظهر هنا.",
  cats:{grc:"الحوكمة والمخاطر والالتزام",pm:"إدارة المشاريع",lss:"لين سيجما ستة",tqm:"الجودة",iso:"مدقق رئيس ISO"},
  certAr:{"Certified GRCP Professional":"محترف معتمد في الحوكمة والمخاطر والالتزام","Certified GRCA Auditor":"مدقق معتمد في الحوكمة والمخاطر والالتزام","PMP":"محترف إدارة المشاريع","Lean Six Sigma Master Black Belt":"الحزام الأسود الماستر","Lean Six Sigma Black Belt":"الحزام الأسود","Lean Six Sigma Green Belt":"الحزام الأخضر","Lean Six Sigma Yellow Belt":"الحزام الأصفر","Total Quality Management":"إدارة الجودة الشاملة","ISO 31000 RM Lead Auditor":"مدير مخاطر","ISO 22301 BCMS Lead Auditor":"مدقق رئيس، استمرارية الأعمال","ISO 45001 OH&S Lead Auditor":"مدقق رئيس، الصحة والسلامة المهنية","ISO 9001 QMS Lead Auditor":"مدقق رئيس، إدارة الجودة","ISO 22000 FSMS Lead Auditor":"مدقق رئيس، سلامة الغذاء"},
  caK:"القدرات المهنية", caH:"القدرات حسب المجال",
  caps:[
    {ic:"qual",t:"الجودة والتميّز",i:["إدارة الجودة الشاملة","سيجما ستة","المنهجية الرشيقة (Lean)","منهجية الهدر السبعة","أدوات الجودة","أنظمة إدارة الجودة"]},
    {ic:"grc",t:"الحوكمة والالتزام",i:["أنظمة إدارة الالتزام","التدقيق","الحوكمة والمخاطر والالتزام","إدارة المخاطر"]},
    {ic:"cx",t:"تجربة العملاء",i:["معالجة شكاوى العملاء","قياس رضا العملاء ومتابعته"]},
    {ic:"iso",t:"أنظمة الإدارة",i:["الصحة والسلامة المهنية","استمرارية الأعمال","إدارة الابتكار"]},
    {ic:"lead",t:"القيادة",i:["القيادة","اتخاذ القرار","حل المشكلات","التدريب","التواصل","تعدد المهام","العمل الجماعي"]}
  ],
  stK:"المعايير والأطر", stH:"معايير دولية في أعمال أحمد", stP:"المعايير وأطر التميّز الموثقة في سيرته الذاتية.",
  std:[["ISO 9001","إدارة الجودة"],["ISO 10002","معالجة شكاوى العملاء"],["ISO 10004","متابعة رضا العملاء"],["ISO 45001","الصحة والسلامة المهنية"],["ISO 56002","إدارة الابتكار"],["ISO 22301","استمرارية الأعمال"],["ISO 31000","إدارة المخاطر"],["ISO 37301","إدارة الالتزام"],["ISO 14001","الإدارة البيئية"],["ISO 17020","تقييم المطابقة، جهات التفتيش"],["EFQM","نموذج التميّز"],["KAQA","جائزة الملك عبدالعزيز للجودة"]],
  stPre:"معيار", stFw:"إطار", stAw:"جائزة",
  trH:"التدريب والتطوير المستمر", trP:"البرامج المذكورة في السيرة الذاتية. اضغط للعرض.",
  train:["التميّز المؤسسي","إدارة الأزمات والمخاطر","التخطيط الاستراتيجي","القيادة التنفيذية","إدارة التغيير","EFQM","جائزة الملك عبدالعزيز للجودة","إدارة المخاطر","معايير ISO"],
  orK:"الجهات والخبرة المهنية", orH:"الجهات التي عمل معها أحمد", orP:"تظهر كل جهة مع طبيعة علاقتها بأحمد كما وردت في السيرة الذاتية.",
  rel:{emp:"جهة عمل",free:"عمل حر",client:"مهمة لدى عميل"},
  orgs:[
    ["MHRSD","وزارة الموارد البشرية والتنمية الاجتماعية","الرياض","emp"],
    ["SAC","المركز السعودي للاعتماد","الرياض","free"],
    ["SDC","شركة تطوير السودة (صندوق الاستثمارات العامة)","الرياض","emp"],
    ["DVT","ديفوتيم DEVOTEAM","الرياض","emp"],
    ["MDN","«مدن»، الهيئة السعودية للمدن الصناعية ومناطق التقنية","عبر ديفوتيم","client"],
    ["AFC","شركة آرو للأغذية Arrow Food Co.","الدمام","emp"],
    ["BTM","بيتومات BITUMAT","الدمام","emp"],
    ["ATL","أطلس ATLAS","الرياض","free"],
    ["NTP","ناتبت NATPET","ينبع","emp"]
  ],
  lgH:"اللغات", langs:[["العربية","Arabic"],["الإنجليزية","English"]],
  dvK:"السيرة الذاتية والملف الرقمي", dvH:"الملف نفسه على كل الشاشات", dvP:"يُعرض هذا الملف بالجودة نفسها على الحاسوب والجهاز اللوحي والجوال. والسيرة الذاتية الكاملة متاحة بصيغة PDF في صفحتين A4 بالعربية والإنجليزية.",
  dvB:"تحميل السيرة الذاتية كاملة", dvB2:"السيرة بالإنجليزية", dvS:"ملف PDF، مقاس A4، صفحتان.",
  coK:"التواصل", coH:"لنتواصل", coP:"مقيم في الرياض، المملكة العربية السعودية. تواصل مع أحمد مباشرة عبر البريد الإلكتروني أو الهاتف أو لينكدإن.",
  ct:[["البريد الإلكتروني","ahshcompany@gmail.com","mailto:ahshcompany@gmail.com"],["الهاتف","+966 53 201 3487","tel:+966532013487"],["لينكدإن","linkedin.com/in/ahmedpq","https://www.linkedin.com/in/ahmedpq"],["الموقع","الرياض، المملكة العربية السعودية",null]],
  foot:"© أحمد بخاري. الملف المهني التنفيذي.", top:"العودة إلى الأعلى",
  copied:"تم النسخ.", copy:"نسخ", dlOk:"بدأ تحميل السيرة الذاتية.", dlNo:"أُلغي التحميل.", dlErr:"تعذّر حفظ السيرة هنا. أعد المحاولة من الصفحة المنشورة."
}};

const CERTS = [
  ["Certified GRCP Professional","grc"],["Certified GRCA Auditor","grc"],["PMP","pm"],
  ["Lean Six Sigma Master Black Belt","lss"],["Lean Six Sigma Black Belt","lss"],["Lean Six Sigma Green Belt","lss"],["Lean Six Sigma Yellow Belt","lss"],
  ["Total Quality Management","tqm"],
  ["ISO 9001 QMS Lead Auditor","iso"],["ISO 45001 OH&S Lead Auditor","iso"],["ISO 22301 BCMS Lead Auditor","iso"],["ISO 31000 RM Lead Auditor","iso"],["ISO 22000 FSMS Lead Auditor","iso"]
];

